# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: 
  push:
    branches:
      - TestingAutoExport

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  export_game:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    name: Export Game Job
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Godot Export
        # You may pin to the exact commit or the version.
        # uses: firebelley/godot-export@1e28506c4afa5c7c33c7da60f87b71ccacf4a405
        uses: firebelley/godot-export@v3.0.0
        with:
          # The download url of the 64 bit Linux Headless Godot executable.
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.4.2/Godot_v3.4.2-stable_linux_headless.64.zip
          # The url of the export templates corresponding to the Godot executable version.
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.4.2/Godot_v3.4.2-stable_export_templates.tpz
          # The relative path containing the "project.godot" file.
          relative_project_path: ./
          # The version which new releases start at.
          base_version: 1.0.0
          # If releases should be automatically created.
          create_release: true
          # If release notes should be automatically generated based on commit history.
          generate_release_notes: true
          # If should export with debugging tools.
          export_debug: false
        
